---
openapi: 3.0.0
info:
  title: autogen_social_api
  version: "1.0.0"
  description: |
    API for content orchestration, generation, and posting for social media automation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api
    description: Azure Functions API endpoint

paths:
  /orchestrate-content:
    post:
      $ref: "./operations/internal/function/generate-content-orchestrator.yaml#/paths/~1orchestrate-content/post"
  /generate-image:
    post:
      $ref: "./operations/internal/function/generate-image.yaml#/paths/~1generate-image/post"
  /generate-content:
    post:
      $ref: "./operations/internal/function/generate-content.yaml#/paths/~1generate-content/post"
  /post-content:
    post:
      $ref: "./operations/internal/function/post-content.yaml#/paths/~1post-content/post"
  /external/post-instagram-content:
    post:
      $ref: "./operations/external/post-instagram-content.yaml#/paths/~1external~1post-instagram-content/post"

components:
  parameters:
    brand_id:
      $ref: "./components/parameters.yaml#/brand_id"
    id:
      $ref: "./components/parameters.yaml#/id"
    pagination:
      $ref: "./components/parameters.yaml#/pagination"
  responses:
    NotFound:
      $ref: "./components/responses.yaml#/NotFound"
    BadRequest:
      $ref: "./components/responses.yaml#/BadRequest"
    Unauthorized:
      $ref: "./components/responses.yaml#/Unauthorized"
    RateLimitExceeded:
      $ref: "./components/responses.yaml#/RateLimitExceeded"
  securitySchemes:
    bearerAuth:
      $ref: "./components/security-schemes.yaml#/bearerAuth"
    ApiKeyAuth:
      $ref: "./components/security-schemes.yaml#/ApiKeyAuth"
  schemas:
    BaseModel:
      $ref: "./schemas/base.yaml#/BaseModel"
    Brand:
      $ref: "./schemas/brand.yaml#/Brand"
    ContentTemplate:
      $ref: "./schemas/content-template.yaml#/ContentTemplate"
    MediaDocument:
      $ref: "./schemas/media.yaml#/MediaDocument"
    MediaMetadata:
      $ref: "./schemas/media.yaml#/MediaMetadata"
    Fonts:
      $ref: "./schemas/common/fonts.yaml#/Fonts"
    Metadata:
      $ref: "./schemas/common/metadata.yaml#/Metadata"
    Schedule:
      $ref: "./schemas/common/schedule.yaml#/Schedule"
    SocialAccount:
      $ref: "./schemas/common/social-account.yaml#/SocialAccount"
    TimeSlot:
      $ref: "./schemas/common/time-slot.yaml#/TimeSlot"
    VisualStyle:
      $ref: "./schemas/common/visual-style.yaml#/VisualStyle"
    Image:
      $ref: "./schemas/content-types/image.yaml#/Image"
    MultiImage:
      $ref: "./schemas/content-types/multi-image.yaml#/MultiImage"
    Text:
      $ref: "./schemas/content-types/text.yaml#/Text"
    Video:
      $ref: "./schemas/content-types/video.yaml#/Video"
    Facebook:
      $ref: "./schemas/platforms/facebook.yaml#/Facebook"
    Instagram:
      $ref: "./schemas/platforms/instagram.yaml#/Instagram"
    TikTok:
      $ref: "./schemas/platforms/tiktok.yaml#/TikTok"
    Twitter:
      $ref: "./schemas/platforms/twitter.yaml#/Twitter"
    AzureOpenAIGenerateContentTemplate:
      $ref: "./schemas/ai/azure-openai-generate-content.yaml#/AzureOpenAIGenerateContentTemplate"
    AzureOpenAIGenerateContentRequest:
      $ref: "./schemas/ai/azure-openai-generate-content.yaml#/AzureOpenAIGenerateContentRequest"
    AzureOpenAIGenerateContentResponse:
      $ref: "./schemas/ai/azure-openai-generate-content.yaml#/AzureOpenAIGenerateContentResponse"
    OrchestratorRequest:
      $ref: "./schemas/function/orchestrator.yaml#/OrchestratorRequest"
    OrchestratorResponse:
      $ref: "./schemas/function/orchestrator.yaml#/OrchestratorResponse"

security:
  - bearerAuth: []
