openapi: 3.0.0
info:
  title: autogen_social_api
  version: '1.0.0'
  description: |
    api for managing brands and content generation templates for social media automation.
    
    ## authentication
    this api uses api key authentication. include your api key in the x-api-key header.
    
    ## rate_limiting
    api calls are limited to 100 requests per minute per api key.
    
    ## error_handling
    all errors follow a standard format:
    ```json
    {
      "error": {
        "code": "error_code",
        "message": "human readable message",
        "details": {} // optional additional information
      }
    }
    ```
  contact:
    name: autogen_social_support
    url: https://autogensocial.com/support
  license:
    name: mit
    url: https://opensource.org/licenses/mit

servers:
  - url: /api
    description: Azure Functions API endpoint
  - url: http://localhost:7071/api
    description: Local development server

tags:
  - name: Brands
    description: Brand management operations
  - name: Content Templates
    description: Content generation template operations

components:
  parameters:
    $ref: './components/parameters.yaml'
  responses:
    $ref: './components/responses.yaml'
  securitySchemes:
    $ref: './components/security-schemes.yaml'
  schemas:
    GenerateContentRequest:
      type: object
      required:
        - brandId
        - templateId
      properties:
        brandId:
          type: string
          format: uuid
        templateId:
          type: string
          format: uuid
        variableValues:
          type: object
          additionalProperties:
            type: string
    GenerateContentResponse:
      type: object
      required:
        - id
        - content
      properties:
        id:
          type: string
        content:
          $ref: './schemas/responses/openai-content-response.yaml#/components/schemas/OpenAIContentResponse'

paths:
  /brand_management:
    post:
      $ref: './paths/brand/create.yaml#/post'
      tags: [Brands]
    get:
      $ref: './paths/brand/get-all.yaml#/get'
      tags: [Brands]
      parameters:
        - $ref: '#/components/parameters/pagination'

  /brand_management/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      $ref: './paths/brand/get-by-id.yaml#/get'
      tags: [Brands]
    put:
      $ref: './paths/brand/update.yaml#/put'
      tags: [Brands]

  /content_generation_template_management:
    post:
      $ref: './paths/content-template/create.yaml#/post'
      tags: [Content Templates]
    get:
      $ref: './paths/content-template/get-all.yaml#/get'
      tags: [Content Templates]
      parameters:
        - $ref: '#/components/parameters/brandId'
        - $ref: '#/components/parameters/pagination'

  /content_generation_template_management/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      $ref: './paths/content-template/get-by-id.yaml#/get'
      tags: [Content Templates]
    put:
      $ref: './paths/content-template/update.yaml#/put'
      tags: [Content Templates]

  /generate_content:
    post:
      summary: Generate content using a template
      tags: [Content Templates]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateContentRequest'
      responses:
        '201':
          description: Content generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateContentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/RateLimitExceeded'
        '500':
          $ref: '#/components/responses/InternalError'

security:
  - ApiKeyAuth: []