openapi: 3.0.0
info:
  title: autogen_social_api
  version: "1.0.0"
  description: |
    API for content orchestration, generation, and posting for social media automation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api
    description: Azure Functions API endpoint

components:
  schemas:
    BrandCreate:
      $ref: './components/schemas/api/internal/brand/BrandCreate.yaml#/BrandCreate'
    BrandDelete:
      $ref: './components/schemas/api/internal/brand/BrandDelete.yaml#/BrandDelete'
    BrandGet:
      $ref: './components/schemas/api/internal/brand/BrandGet.yaml#/BrandGet'
    BrandResponse:
      $ref: './components/schemas/api/internal/brand/BrandResponse.yaml#/BrandResponse'
    BrandUpdate:
      $ref: './components/schemas/api/internal/brand/BrandUpdate.yaml#/BrandUpdate'
    ContentGenerationTemplateCreate:
      $ref: './components/schemas/api/internal/content-generation-template/ContentGenerationTemplateCreate.yaml#/ContentGenerationTemplateCreate'
    ContentGenerationTemplateDelete:
      $ref: './components/schemas/api/internal/content-generation-template/ContentGenerationTemplateDelete.yaml#/ContentGenerationTemplateDelete'
    ContentGenerationTemplateGet:
      $ref: './components/schemas/api/internal/content-generation-template/ContentGenerationTemplateGet.yaml#/ContentGenerationTemplateGet'
    ContentGenerationTemplateResponse:
      $ref: './components/schemas/api/internal/content-generation-template/ContentGenerationTemplateResponse.yaml#/ContentGenerationTemplateResponse'
    ContentGenerationTemplateUpdate:
      $ref: './components/schemas/api/internal/content-generation-template/ContentGenerationTemplateUpdate.yaml#/ContentGenerationTemplateUpdate'
    BaseModel:
      $ref: './components/schemas/common/base/BaseModel.yaml#/BaseModel'
    BrandInfo:
      $ref: './components/schemas/common/base/BrandInfo.yaml#/BrandInfo'
    ContentItem:
      $ref: './components/schemas/common/base/ContentItem.yaml#/ContentItem'
    ContentType:
      $ref: './components/schemas/common/base/ContentType.yaml#/ContentType'
    Metadata:
      $ref: './components/schemas/common/base/Metadata.yaml#/Metadata'
    Text:
      $ref: './components/schemas/common/base/Text.yaml#/Text'
    CognitiveBrand:
      $ref: './components/schemas/common/cognitive/CognitiveBrand.yaml#/CognitiveBrand'
    CognitiveCaption:
      $ref: './components/schemas/common/cognitive/CognitiveCaption.yaml#/CognitiveCaption'
    CognitiveCategory:
      $ref: './components/schemas/common/cognitive/CognitiveCategory.yaml#/CognitiveCategory'
    CognitiveData:
      $ref: './components/schemas/common/cognitive/CognitiveData.yaml#/CognitiveData'
    CognitiveDenseCaption:
      $ref: './components/schemas/common/cognitive/CognitiveDenseCaption.yaml#/CognitiveDenseCaption'
    CognitiveObject:
      $ref: './components/schemas/common/cognitive/CognitiveObject.yaml#/CognitiveObject'
    CognitivePerson:
      $ref: './components/schemas/common/cognitive/CognitivePerson.yaml#/CognitivePerson'
    CognitiveTag:
      $ref: './components/schemas/common/cognitive/CognitiveTag.yaml#/CognitiveTag'
    Rectangle:
      $ref: './components/schemas/common/cognitive/Rectangle.yaml#/Rectangle'
    Image:
      $ref: './components/schemas/common/media/Image.yaml#/Image'
    MediaMetadata:
      $ref: './components/schemas/common/media/MediaMetadata.yaml#/MediaMetadata'
    MediaType:
      $ref: './components/schemas/common/media/MediaType.yaml#/MediaType'
    MultiImage:
      $ref: './components/schemas/common/media/MultiImage.yaml#/MultiImage'
    Video:
      $ref: './components/schemas/common/media/Video.yaml#/Video'
    Schedule:
      $ref: './components/schemas/common/schedule/Schedule.yaml#/Schedule'
    TimeSlot:
      $ref: './components/schemas/common/schedule/TimeSlot.yaml#/TimeSlot'
    Platform:
      $ref: './components/schemas/common/social/Platform.yaml#/Platform'
    SocialAccount:
      $ref: './components/schemas/common/social/SocialAccount.yaml#/SocialAccount'
    SocialAccountEntry:
      $ref: './components/schemas/common/social/SocialAccountEntry.yaml#/SocialAccountEntry'
    Alignment:
      $ref: './components/schemas/common/style/Alignment.yaml#/Alignment'
    Font:
      $ref: './components/schemas/common/style/Font.yaml#/Font'
    Fonts:
      $ref: './components/schemas/common/style/Fonts.yaml#/Fonts'
    Outline:
      $ref: './components/schemas/common/style/Outline.yaml#/Outline'
    OverlayBox:
      $ref: './components/schemas/common/style/OverlayBox.yaml#/OverlayBox'
    TextStyle:
      $ref: './components/schemas/common/style/TextStyle.yaml#/TextStyle'
    VisualStyle:
      $ref: './components/schemas/common/style/VisualStyle.yaml#/VisualStyle'
    VisualStyleObj:
      $ref: './components/schemas/common/style/VisualStyleObj.yaml#/VisualStyleObj'
    PromptTemplate:
      $ref: './components/schemas/common/template/PromptTemplate.yaml#/PromptTemplate'
    PromptVariable:
      $ref: './components/schemas/common/template/PromptVariable.yaml#/PromptVariable'
    TemplateInfo:
      $ref: './components/schemas/common/template/TemplateInfo.yaml#/TemplateInfo'
    TemplateSettings:
      $ref: './components/schemas/common/template/TemplateSettings.yaml#/TemplateSettings'
    BrandDocument:
      $ref: './components/schemas/documents/BrandDocument.yaml#/BrandDocument'
    ContentGenerationTemplateDocument:
      $ref: './components/schemas/documents/ContentGenerationTemplateDocument.yaml#/ContentGenerationTemplateDocument'
    MediaDocument:
      $ref: './components/schemas/documents/MediaDocument.yaml#/MediaDocument'
    PostDocument:
      $ref: './components/schemas/documents/PostDocument.yaml#/PostDocument'

paths:
  /external/post-instagram-content:
    post:
      $ref: './operations/external/post-instagram-content.yaml#/paths//external/post-instagram-content/post'
  /internal/frontend/brand:
    post:
      $ref: './operations/internal/frontend/brand.yaml#/paths//internal/frontend/brand/post'
  /internal/frontend/content-generation-template:
    post:
      $ref: './operations/internal/frontend/content-generation-template.yaml#/paths//internal/frontend/content-generation-template/post'
  /internal/function/generate-content-orchestrator:
    post:
      $ref: './operations/internal/function/generate-content-orchestrator.yaml#/paths//internal/function/generate-content-orchestrator/post'
  /internal/function/generate-content:
    post:
      $ref: './operations/internal/function/generate-content.yaml#/paths//internal/function/generate-content/post'
  /internal/function/generate-image:
    post:
      $ref: './operations/internal/function/generate-image.yaml#/paths//internal/function/generate-image/post'
  /internal/function/post-content:
    post:
      $ref: './operations/internal/function/post-content.yaml#/paths//internal/function/post-content/post'

security:
  - bearerAuth: []
