# OpenAPI schema for the /generate-image endpoint request body, aligned with Pillow-based function
openapi: 3.0.0
info:
  title: Generate Image Request
  version: '1.0.0'
  description: Schema for image generation input compatible with Pillow.
components:
  schemas:
    GenerateImageRequest:
      allOf:
        - $ref: '../../schemas/content-types/image.yaml'
        - type: object
          required:
            - text
            - visualStyle
            - imageLayout
          properties:
            text:
              type: string
              description: Main text to render on the image.
            boxText:
              type: string
              description: Optional text to render in the box below the image.
            visualStyle:
              $ref: '../../schemas/common/visual-style.yaml'
            imageLayout:
              type: object
              required:
                - width
                - height
              properties:
                width:
                  type: integer
                  description: Width of the image in pixels.
                height:
                  type: integer
                  description: Height of the image in pixels.
                boxHeight:
                  type: integer
                  description: Height of the box below the image (default 80).
            imageFormat:
              type: string
              enum: [PNG, JPEG]
              default: PNG
              description: Output image format.
