brandId:
  name: brandId
  in: query
  required: true
  schema:
    type: string
    format: uuid
  description: Brand identifier (UUID)

id:
  name: id
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: Resource identifier (UUID)

pagination:
  in: query
  name: pagination
  required: false
  schema:
    type: object
    properties:
      limit:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      offset:
        type: integer
        minimum: 0
        default: 0
      sortBy:
        type: string
        enum: [createdAt, updatedAt, name]
        default: createdAt
      sortOrder:
        type: string
        enum: [asc, desc]
        default: desc
  description: Pagination and sorting parameters

filter:
  name: filter
  in: query
  required: false
  schema:
    type: string
  description: Filter criteria in the format field:operator:value (e.g., name:contains:test)
  example: "name:contains:acme"