---
brand_id:
  name: brand_id
  in: query
  required: true
  schema:
    type: string
    format: uuid
  description: brand identifier (uuid)
id:
  name: id
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: resource identifier (uuid)
pagination:
  in: query
  name: pagination
  required: false
  schema:
    type: object
    properties:
      limit:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      offset:
        type: integer
        minimum: 0
        default: 0
      sort_by:
        type: string
        enum: [created_at, updated_at, name]
        default: created_at
      sort_order:
        type: string
        enum: [asc, desc]
        default: desc
filter:
  name: filter
  in: query
  required: false
  schema:
    type: string
  description: filter criteria in the format field:operator:value (e.g., name:contains:test)
  example: "name:contains:acme"
