openapi: 3.0.0
info:
  title: Image Generation API
  version: 1.0.0
paths:
  /generate-image:
    post:
      operationId: generateImage
      summary: Generate an image
      description: Generates an image based on provided text and style options, including advanced font management and background image centering.
      tags:
        - ContentGeneration
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../schemas/content-types/image.yaml'
      responses:
        '200':
          description: Image generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    description: URL of the generated image
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
