openapi: 3.0.0
components:
  schemas:
    ContentType:
      type: string
      enum: [text, video, multi-image, image]
      description: Type of content to be generated - text (text-only post), video (video content), multi-image (multiple images), image (single image)

    Platform:
      type: array
      items:
        type: string
        enum: [instagram, facebook, tiktok, twitter]
        description: Social media platform(s) for the content

    PromptVariable:
      type: object
      required:
        - name
        - values
      properties:
        name:
          type: string
          description: Name of the variable
        values:
          type: array
          items:
            type: string
          description: Possible values for the variable
        description:
          type: string
          description: Optional description of the variable

    TemplateSettings:
      type: object
      required:
        - prompt_template
        - visual_style
        - image
      properties:
        prompt_template:
          type: object
          required:
            - system_prompt
            - user_prompt
            - model
          properties:
            system_prompt:
              type: string
              description: System-level instructions for the AI.
            user_prompt:
              type: string
              description: The main prompt for content generation. Uses {{variable}} syntax.
            temperature:
              type: number
              minimum: 0
              maximum: 2
              default: 1
            max_tokens:
              type: integer
            model:
              type: string
            variables:
              type: array
              items:
                $ref: '#/components/schemas/PromptVariable'
        visual_style:
          type: object
          properties:
            themes:
              type: array
              minItems: 1
              items:
                $ref: '../../schemas/common/visual-style.yaml'
        image:
          $ref: '../../schemas/content-types/image.yaml'

    TemplateInfo:
      type: object
      required:
        - name
        - brandId
        - contentType
        - targetPlatforms
      properties:
        name:
          type: string
        description:
          type: string
        brandId:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        targetPlatforms:
          type: array
          items:
            type: string
            enum: [instagram, facebook, tiktok, twitter]

    ContentGenerationTemplate:
      allOf:
        - $ref: './base.yaml#/components/schemas/BaseModel'
        - type: object
          required:
            - templateInfo
            - schedule
            - settings
          properties:
            templateInfo:
              $ref: '#/components/schemas/TemplateInfo'
            schedule:
              $ref: '../../schemas/common/schedule.yaml'
            settings:
              $ref: '#/components/schemas/TemplateSettings'

    ContentTemplateCreate:
      type: object
      required:
        - templateInfo
        - schedule
        - settings
      properties:
        templateInfo:
          $ref: '#/components/schemas/TemplateInfo'
        schedule:
          $ref: '../../schemas/common/schedule.yaml'
        settings:
          $ref: '#/components/schemas/TemplateSettings'

    ContentTemplateUpdate:
      type: object
      properties:
        templateInfo:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            contentType:
              $ref: '#/components/schemas/ContentType'
            brandId:
              type: string
        schedule:
          $ref: '../../schemas/common/schedule.yaml'
        settings:
          $ref: '#/components/schemas/TemplateSettings'
