openapi: 3.0.0
components:
  schemas:
    ContentType:
      type: string
      enum: [text, video, multi-image, image]
      description: Type of content to be generated - text (text-only post), video (video content), multi-image (multiple images), image (single image)

    Platform:
      type: array
      items:
        type: string
        enum: [instagram, facebook, tiktok, twitter]
        description: Social media platform(s) for the content

    PromptVariable:
      type: object
      required:
        - name
        - values
      properties:
        name:
          type: string
          description: Name of the variable
        values:
          type: array
          items:
            type: string
          description: Possible values for the variable

    TemplateSettings:
      type: object
      required:
        - promptTemplate
        - visualStyle
      properties:
        promptTemplate:
          type: object
          required:
            - systemPrompt
            - userPrompt
            - model
            - temperature
            - maxTokens
          properties:
            systemPrompt:
              type: string
              description: |
                System-level instructions for the AI. (Set automatically based on content type.)
            userPrompt:
              type: string
              description: |
                The main prompt for content generation. Uses {{variable}} syntax.
            temperature:
              type: number
              minimum: 0
              maximum: 2
              default: 1
              description: Set automatically.
            maxTokens:
              type: integer
              description: Set automatically.
            model:
              type: string
              description: Set automatically.
            variables:
              type: array
              items:
                $ref: '#/components/schemas/PromptVariable'
              description: |
                List of variables available for use in the userPrompt and systemPrompt.
        visualStyle:
          type: object
          description: |
            One or more visual style themes for the generated image. Each theme must match the structure in visual-style.yaml.
          properties:
            themes:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  font:
                    $ref: './common/fonts.yaml'
                  fontSize:
                    type: integer
                    description: Font size for the theme
                  color:
                    type: string
                    description: Main text color for the theme
                  outlineColor:
                    type: string
                    description: Outline color for the theme
                  outlineWidth:
                    type: integer
                    description: Outline width for the theme
                  alignment:
                    type: string
                    enum: [left, center, right]
                    description: Text alignment for the theme
                  backgroundColor:
                    type: string
                    description: Background color for the theme (used if image.backgroundType is 'color')
                required:
                  - font
                  - fontSize
                  - color
                  - backgroundColor
                description: Visual style theme for the template, including background color.
              description: List of visual style themes for this template.
        image:
          type: object
          properties:
            aspectRatio:
              type: string
              enum: ["1:1", "4:5", "16:9", "9:16"]
              description: Aspect ratio for the generated image
            backgroundType:
              type: string
              enum: [color, image]
              description: Whether the background is a color or an image
            backgroundImageUrl:
              type: string
              description: Background image URL (if backgroundType is image and imageSourceType is set)
            imageSourceType:
              type: string
              enum: [set, variable]
              description: If backgroundType is image, determines if the image is a fixed URL (set) or variable (variable)
            variableImageType:
              type: string
              enum: [uploaded, online]
              description: If imageSourceType is variable, determines if the image is uploaded or online
            containerPadding:
              type: integer
              minimum: 0
              maximum: 100
              description: Padding inside the image container
            textBoxHorizontalAlignment:
              type: string
              enum: [left, center, right]
              description: Horizontal alignment for the text box
            textBoxVerticalAlignment:
              type: string
              enum: [top, center, bottom]
              description: Vertical alignment for the text box
          required:
            - aspectRatio
            - backgroundType
            - containerPadding
          description: |
            Image settings for the generated image. If backgroundType is 'color', the background color is taken from the selected visual style theme's backgroundColor. If backgroundType is 'image', you must specify imageSourceType. If imageSourceType is 'variable', you must specify variableImageType.

    TemplateInfo:
      type: object
      required:
        - name
        - brandId
        - contentType
        - targetPlatforms
      properties:
        name:
          type: string
          description: Name of the template
        description:
          type: string
          description: Optional description of the template
        brandId:
          type: string
          description: ID of the brand this template belongs to
        contentType:
          $ref: '#/components/schemas/ContentType'
        targetPlatforms:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
          minItems: 1
          description: List of platforms this template targets

    ContentGenerationTemplate:
      allOf:
        - $ref: './base.yaml#/components/schemas/BaseModel'
        - type: object
          required:
            - templateInfo
            - schedule
            - settings
          properties:
            templateInfo:
              $ref: '#/components/schemas/TemplateInfo'
            schedule:
              $ref: './common/schedule.yaml'
            settings:
              $ref: '#/components/schemas/TemplateSettings'

    ContentTemplateCreate:
      type: object
      required:
        - templateInfo
        - schedule
        - settings
      properties:
        templateInfo:
          $ref: '#/components/schemas/TemplateInfo'
        schedule:
          $ref: './common/schedule.yaml'
        settings:
          $ref: '#/components/schemas/TemplateSettings'

    ContentTemplateUpdate:
      type: object
      properties:
        templateInfo:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            contentType:
              $ref: '#/components/schemas/ContentType'
        schedule:
          $ref: './common/schedule.yaml'
        settings:
          $ref: '#/components/schemas/TemplateSettings'
