openapi: 3.0.0
info:
  title: Instagram Content Posting API
  version: 1.0.0
paths:
  /external/post-instagram-content:
    post:
      operationId: postInstagramContent
      summary: Post content to Instagram
      description: Posts content (text and image) to Instagram for a given brand.
      tags:
        - External
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - brandId
                - imageUrl
                - content
              properties:
                brandId:
                  type: string
                  description: The brand ID for which to post content.
                imageUrl:
                  type: string
                  description: The URL of the image to post.
                content:
                  type: object
                  description: Content object containing comment and hashtags.
                  properties:
                    comment:
                      type: string
                    hashtags:
                      type: array
                      items:
                        type: string
                postId:
                  type: string
                  description: Optional post ID for tracking.
      responses:
        '200':
          description: Content posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Instagram post ID
                  status:
                    type: string
                    description: Post status (e.g., posted, failed)
                  result:
                    type: object
                    description: Raw Instagram API response
        '404':
          description: Instagram account not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
